### PR TITLE
[FIX] 3.2.2 compatibility by accepting positional and keywords args

### LINKED ISSUE #4: Ruby 3.2.2 compatibility
for services like

```ruby
class A < Serviz::Base
  def initialize(foo, bar:)
  end

  def call
  end
end
```

we will get a `wrong number of arguments (given 2, expected 1)` error any time we call `A.call(1, bar: true)`

### PR DESCRIPTION
**Pull request by araluce**
This closes #4

### CODE REVIEW

File: lib/serviz.rb [hunk 1]
```diff
@@ -4,8 +4,14 @@ module Serviz
...
-    def self.call(*args)
-      instance = new(*args)
+    def self.call(*args, **kwargs)
+      instance = if args.length > 0 && kwargs.length > 0
+                   new(*args, **kwargs)
+                 elsif kwargs.length > 0
+                   new(**kwargs)
+                 else
+                   new(*args)
+                 end
```
Comment (araluce) [inline lib/serviz.rb:14]: not a fancy code, but this is mainly the idea.

**Comment by markets** [comment]
Thank you so much @araluce!

**Review by markets — APPROVED** [review]
